apiVersion: v2
name: dras
description: Helm chart for dras — NEXRAD radar monitoring with optional renderer
type: application
version: 2.13.1
appVersion: v2.13.1
home: https://github.com/jacaudi/dras
sources:
  - https://github.com/jacaudi/dras
maintainers:
  - name: jacaudi
dependencies:
  - name: app-template
    version: 5.0.1
    repository: oci://ghcr.io/bjw-s-labs/helm
