version: 2
project_name: "dras"
archives:
  - id: main
    wrap_in_directory: true
    files:
      - "README.md"
builds:
  - env: 
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
changelog:
  sort: asc
release:
  github:
    owner: jacaudi
    name: dras