---
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: dras
builds:
  - dir: ./dras
    main: .
    binary: dras
    ldflags:
      - -X github.com/jacaudi/dras/internal/version.Version={{.Version}}
      - -X github.com/jacaudi/dras/internal/version.BuildTime={{.Date}}
      - -X github.com/jacaudi/dras/internal/version.GitCommit={{.FullCommit}}
      - -X github.com/jacaudi/dras/internal/version.GitBranch={{.Branch}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}"
checksum:
  name_template: "checksums.txt"
release:
  disable: true
changelog:
  disable: true