---
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: dras
builds:
  - env: 
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"
checksum:
  name_template: "checksums.txt"
changelog:
  sort: asc