version: 2
project_name: "dras"
archives:
  - id: main
    wrap_in_directory: true
    files:
      - "README.md"
builds:
  - env: 
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
changelog:
  use: github
  sort: asc
  format: "{{.SHA}}: {{.Message}} (@{{.AuthorUsername}})"
  abbrev: -1
release: 
  github:
    owner: user
    name: repo
  name_template: "{{ .Tag }}"
  body: |
      {{ .Changelog }}
      The following Docker images are available for this release:
      - `docker pull ghcr.io/jacaudi/dras:{{ .Version }}`