---
name: On Merge

on:
  push:
    branches:
      - main

jobs:
  lint:
    uses: jacaudi/github-actions/.github/workflows/component-lint.yml@v0.15.3
    with:
      go: true
    secrets: inherit

  test:
    uses: jacaudi/github-actions/.github/workflows/component-test.yml@v0.15.3
    with:
      test-framework: go
      coverage: true
    secrets: inherit

  release:
    needs: [lint, test]
    uses: jacaudi/github-actions/.github/workflows/component-semantic-release.yml@v0.15.3
    with:
      use-github-app: true
      allow-initial-development-versions: true
      hooks: goreleaser
      changelog-file: CHANGELOG.md
      prepend: true
      validate-config: true
    permissions:
      contents: write
    secrets:
      app-id: ${{ secrets.APP_ID }}
      app-private-key: ${{ secrets.APP_PRIVATE_KEY }}

  pipeline-summary:
    if: always()
    needs: [lint, test, release]
    uses: jacaudi/github-actions/.github/workflows/component-pipeline-summary.yml@v0.15.3
    secrets: inherit
