---
name: Versioned Release

on:
  push:
    tags:
      - v*

jobs:
  docker-build:
    uses: jacaudi/github-actions/.github/workflows/component-container-build.yml@v0.16.1
    with:
      registry: ghcr.io
      platforms: linux/amd64,linux/arm64
      push: true
    permissions:
      contents: read
      packages: write
    secrets: inherit

  pipeline-summary:
    if: always()
    needs: [docker-build]
    uses: jacaudi/github-actions/.github/workflows/component-pipeline-summary.yml@v0.16.1
    secrets: inherit
